- name: Configure containers on app server
  hosts: appserver
  connection: ssh
  become: true

  tasks:
    # Setup secrets so containers can have access to GCP resources 
    - name: Create secrets directory
      file:
        path: "/srv/secrets"
        state: "directory"
        mode: 0755 # Change to 0700
    - name: Copy service account key file
      copy:
        src: ../../secrets/neurodiff-gcp-service.json
        dest: "/srv/secrets/neurodiff-gcp-service.json"
        mode: 0644
    - name: Authenticate gcloud using service account
      shell: "gcloud auth activate-service-account --key-file /srv/secrets/neurodiff-gcp-service.json"
    - name: Copy docker tag file
      copy:
        src: docker-tag
        dest: ~/.docker-tag
        mode: 0644
    - name: "Get docker tag"
      shell: "cat ~/.docker-tag"
      register: tag
    - name: Print tag
      debug:
        var: tag
    # Create common network for all containers
    - name: Create network
      docker_network:
          name: "{{docker_network_name}}"
          driver: "bridge"
          attachable: "yes"
    
    - name: Create frontend container
      docker_container:
        name: "hub-frontend"
        image: "gcr.io/{{ gcp_project }}/hub-frontend:{{ tag.stdout}}"
        state: started
        recreate: yes
        pull: yes
        restart: yes
        published_ports:
          - 3000:80
        networks:
          - name: "{{docker_network_name}}"

    # Create a folder on persistent disk for db data
    - name: Create data directory
      file:
        path: "/mnt/disk-1/data"
        state: "directory"
        mode: 0777
    - name: Create model store directory
      file:
        path: "/mnt/disk-1/model-store"
        state: "directory"
        mode: 0777

    # Create Postgress DB container
    - name: Create postgres container
      docker_container:
        name: "postgres"
        image: "postgres:latest"
        state: started
        recreate: yes
        published_ports:
          - 5432:5432
        env:
          POSTGRES_USER: "neurodiffhub"
          POSTGRES_PASSWORD: "diffeq"
          POSTGRES_DB: "neurodiffhubdb"
        networks:
          - name: "{{docker_network_name}}"
        volumes:
          - /mnt/disk-1/data:/var/lib/postgresql/data # Data folder in persistent drive
  
    - name: Copy db migration scripts
      copy:
        src: "../../database-server/db"
        dest: "/conf"

    - name: Run DB migrations using dbmate
      shell: docker run --rm -it -v /conf/db:/db -e DATABASE_URL=postgres://neurodiffhub:diffeq@postgres/neurodiffhubdb?sslmode=disable --network "{{docker_network_name}}" amacneil/dbmate up

    - name: Create api-service container
      docker_container:
        name: "api-service"
        image: "gcr.io/{{ gcp_project }}/api-service:{{ tag.stdout}}"
        state: started
        recreate: yes
        published_ports:
          - 9000:9000
        env:
          DATABASE_URL: "postgres://neurodiffhub:diffeq@postgres/neurodiffhubdb"
          MODELSTORE_BUCKET: "/modelstore"
        networks:
          - name: "{{docker_network_name}}"
        volumes:
          - /mnt/disk-1/model-store:/modelstore
  
    - name: Check if containers are running
      shell: docker ps
    
    # - name: "Remove all unused containers"
    #   shell: docker system prune -a -f